CREATE TABLE IF NOT EXISTS INVENTORY
(
    SLOT BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR( 128 ) NOT NULL,
    DATA VARBINARY( 65535 ) NOT NULL,
    SIZE BIGINT UNSIGNED NOT NULL
)
;
CREATE UNIQUE INDEX IF NOT EXISTS DATA_INDEX ON INVENTORY( DATA )
;